# Exercises pandas Series

In [1]:
#Import the necessary packages
import pandas as pd




## 1. Train delay
### Part 1

`delay_data` is a dictionary containing the average delay (in minutes) the trains of a certain station have. 
* Create a Series `train_delay` using this dictionary

In [3]:
delay_data = {"Brussel": 6.34, "Antwerpen": 5.45, "Brugge": 4.12, "Gent": 2.45, "Hasselt": 6.08}
train_delay = pd.Series(delay_data)
train_delay
# Your code

Brussel      6.34
Antwerpen    5.45
Brugge       4.12
Gent         2.45
Hasselt      6.08
dtype: float64

Some cities have several stations, which is not specified in the dictionary. Change the index of Brussel, Antwerpen and Gent, to Brussel-Centraal, Antwerpen-Centraal and Gent-Sint-Pieters respectively.

In [41]:
# Your code
train_delay.index = ["Brussel-Centraal","Antwerpen-Centraal","Brugge", "Gent-Sint-Pieters", "Hasselt"]
train_delay

Brussel-Centraal      6.34
Antwerpen-Centraal    5.45
Brugge                4.12
Gent-Sint-Pieters     2.45
Hasselt               6.08
dtype: float64

* Create a new Series only containing the data of Brussels and Gent.

In [62]:
# Your code
delay_sh = pd.Series(delay_data, index=["Brussel", "Gent"])
print(delay_sh)
print(train_delay)


Brussel    6.34
Gent       2.45
dtype: float64
Brussel-Centraal      8.34
Antwerpen-Centraal    5.45
Brugge                4.12
Gent-Sint-Pieters     2.45
Hasselt               6.08
dtype: float64


### Train delay part 2

* Display the average delay time of Antwerpen.

In [61]:

# Your code
delay_ant = delay_data["Antwerpen"]
delay_ant

5.45

Rumors say that train company *Chuck Chuck* only labels a train as delayed when they arrive at least 6 minutes late. Filter the series to only show the stations with an average delay of at least 6 minutes. Save the resulting Series in a new variable.

In [59]:
# Your code
six_plus = train_delay[train_delay >= 6]
six_plus

Brussel-Centraal    8.34
Hasselt             6.08
dtype: float64

Oops, there was a wrong data entry in the data set. The average train delay in Brussel-Centraal is not 6.34 min but 8.34 min. Change the data of our Series train_delay.

In [53]:
# Your code
train_delay["Brussel-Centraal"] = 8.34
train_delay

Brussel-Centraal      8.34
Antwerpen-Centraal    5.45
Brugge                4.12
Gent-Sint-Pieters     2.45
Hasselt               6.08
dtype: float64

Display following data using the appropriate attribute.
* The indices of the Series
* The values of the Series
* How many values the Series contains
* The datatype of the elements of the Series

In [63]:
# Your code
print(train_delay.index)
print(train_delay.values)
print(train_delay.size)
print(train_delay.dtype)

Index(['Brussel-Centraal', 'Antwerpen-Centraal', 'Brugge', 'Gent-Sint-Pieters',
       'Hasselt'],
      dtype='object')
[8.34 5.45 4.12 2.45 6.08]
5
float64


## 2. Zoo animals

`Animal_counts` is a dictionary containing the amount of animals of a certain type are living in the local zoo. 


In [110]:
animal_counts = {
    "Lion": 5,
    "Elephant": 3,
    "Giraffe": 7,
    "Zebra": 12,
    "Kangaroo": 4,
    "Penguin": 15,
    "Panda": 2,
    "Tiger": 6,
    "Flamingo": 8,
    "Crocodile": 3
}

**Basic Series operations**
* Create a Series `zoo_animals` using this dictionary
* Show how many Giraffes and Tigers there are.
* Print the total number of animals in the zoo.
* Print the list of animal species.
* Print the list of animal counts.

In [115]:
# Your code
zoo_animals = pd.Series(animal_counts)
gir_tig = pd.Series(zoo_animals, index=["Giraffe", "Tiger"])
print(gir_tig)
print("Total number of animals in the zoo:", zoo_animals.sum())
print(zoo_animals.index)
print(zoo_animals.values)

Giraffe    7
Tiger      6
dtype: int64
Total number of animals in the zoo: 65
Index(['Lion', 'Elephant', 'Giraffe', 'Zebra', 'Kangaroo', 'Penguin', 'Panda',
       'Tiger', 'Flamingo', 'Crocodile'],
      dtype='object')
[ 5  3  7 12  4 15  2  6  8  3]


**Filtering and data manipulation**
* Display the animals who are at least with 5 of their kind.
* Create a new Series only containing the data of the animals with a count of 3 or less.
* Jippieeee! A panda was born! Increase the number of pandas with 1.
* Joan the Crocodile has found a lover in the Berlin zoo and moves together with their 2 mates to Berlin. Remove the crocodile data from the Series.
* Oops, we forgot to count the Koala's. Add 3 koala's to the Series.

In [120]:
# Your code
zoo_animals = pd.Series(animal_counts)

print("Display the animals who are at least with 5 of their kind.")
print(zoo_animals[zoo_animals >= 5])

print("Create a new Series only containing the data of the animals with a count of 3 or less.")
three_or_less = zoo_animals[zoo_animals <= 3]
print(three_or_less)

print("Increase the number of pandas with 1.")
zoo_animals["Panda"] +=1
print(zoo_animals)

print("Remove the crocodile data from the Series.")
zoo_animals = zoo_animals.drop(labels=["Crocodile"])
print(zoo_animals)

print("Add 3 koala's to the Series.")
zoo_animals["Koala"] = 3
print(zoo_animals)



Display the animals who are at least with 5 of their kind.
Lion         5
Giraffe      7
Zebra       12
Penguin     15
Tiger        6
Flamingo     8
dtype: int64
Create a new Series only containing the data of the animals with a count of 3 or less.
Elephant     3
Panda        2
Crocodile    3
dtype: int64
Increase the number of pandas with 1.
Lion          5
Elephant      3
Giraffe       7
Zebra        12
Kangaroo      4
Penguin      15
Panda         3
Tiger         6
Flamingo      8
Crocodile     3
dtype: int64
Remove the crocodile data from the Series.
Lion         5
Elephant     3
Giraffe      7
Zebra       12
Kangaroo     4
Penguin     15
Panda        3
Tiger        6
Flamingo     8
dtype: int64
Add 3 koala's to the Series.
Lion         5
Elephant     3
Giraffe      7
Zebra       12
Kangaroo     4
Penguin     15
Panda        3
Tiger        6
Flamingo     8
Koala        3
dtype: int64
